app/models/Post.py
"""
.. module:: Post
    :synopsis: A generic post database model.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

from app import db
from app.models import User
from app.lib.regex import SLUG_REGEX
from datetime import datetime
import markdown
now = datetime.now

class Post(db.Document):
    """A generic post object.

    :ivar date_created: :class:`mongoengine.fields.DateTimeField` - The date
        the post was created.
    :ivar date_modified: :class:`mongoengine.fields.DateTimeField` - The date
        the post was last modified.
    :ivar title: :class:`mongoengine.fields.StringField` - The title of the
        post.
    :ivar author: :class:`mongoengine.fields.ReferenceField` - The author of
        the post.
    :ivar html_content: :class:`mongoengine.fields.StringField` - The HTML body
        of the post.
    :ivar markdown_content: :class:`mongoengine.fields.StringField` - The
        markdown body of the post, which will be rendered to HTML.
    :ivar images: :class:`mongoengine.fields.ListField` of
        :class:`mongoengine.fields.ReferenceField` - The images for this blog
        post.
    :ivar featured_image: :class:`mongoengine.fields.ReferenceField` - The
        featured image on this post.
    :ivar slug: :class:`mongoengine.fields.StringField` - The URL slug
        associated with this post.
    :ivar categories: :class:`mongoengine.fields.ListField` of
        :class:`mongoengine.fields.StringField` - A list of categories for this
        post.
    :ivar tags: :class:`mongoengine.fields.ListField` of
        :class:`mongoengine.fields.StringField` - A list of tags for this post.
    :ivar published: :class:`mongoengine.fields.BooleanField` - True if the
        event is published.
    :ivar date_published: :class:`mongoengine.fields.DateTimeField` - The date
        when this post was published.
    :ivar posted_by: :class:`mongoengine.fields.ReferenceField` - The user that
        posted this event. This may be different than the post's author, if the
        author was a guest writer or someone not registered with Eventum.
    """

    # MongoEngine ORM metadata
    meta = {
        'allow_inheritance': True,
        'indexes': ['title', 'date_created'],
        'ordering': ['-date_created']
    }

    date_created = db.DateTimeField(required=True, default=now)
    date_modified = db.DateTimeField(required=True, default=now)
    title = db.StringField(required=True, max_length=255)
    author = db.ReferenceField(User, required=True)
    html_content = db.StringField()
    markdown_content = db.StringField(required=True)
    images = db.ListField(db.ReferenceField('Image'))
    featured_image = db.ReferenceField('Image')
    slug = db.StringField(required=True, regex=SLUG_REGEX)
    categories = db.ListField(db.StringField(db_field='category',
                                             max_length=255),
                              default=list)
    tags = db.ListField(db.StringField(db_field='tag', max_length=255),
                        default=list)
    published = db.BooleanField(required=True, default=False)
    date_published = db.DateTimeField()
    posted_by = db.ReferenceField(User, required=True)

    def id_str(self):
        """The id of this object, as a string.

        :returns: The id
        :rtype: str
        """
        return str(self.id)

    def clean(self):
        """Called by Mongoengine on every ``.save()`` to the object.

        Update date_modified, and fill in posted_by and html_content
        if invalid.

        :raises: :class:`wtforms.validators.ValidationError`
        """

        self.date_modified = now()

        self.html_content = markdown.markdown(self.markdown_content,
                                              ['extra', 'smarty'])
        if self.images:
            for image in self.images:
                self.html_content = self.html_content.replace(
                    'src="' + image.filename + '"',
                    'src="' + image.url() + '"')
        if not self.posted_by:
            self.posted_by = self.author
        if self.published and not self.date_published:
            self.date_published = now()

    def __unicode__(self):
        """This post, as a unicode string.

        :returns: The title of the post
        :rtype: str
        """
        return self.title

    def __repr__(self):
        """The representation of this post.

        :returns: The post's details.
        :rtype: str
        """
        rep = '%r(title=%r, author=%r, categories=%r, tags=%r, published=%r' %\
            (self.__class__.__name__, self.title, self.author, self.categories,
             self.tags, self.published)

        # excluded if None
        rep += ', date_published=%r' % (self.date_published) \
            if self.date_published else ""
        rep += ', posted_by=%r' % (self.posted_by) if self.posted_by else ""

        # cut down to 100 characters
        if len(self.html_content) > 100:
            rep += ', html_content=%r' % (self.html_content[:97] + "...")
        else:
            rep += ', html_content=%r' % (self.html_content)
        return rep

app/routes/blog.py
"""
.. module:: blog
    :synopsis: All routes on the ``blog`` Blueprint.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

from flask import Blueprint, render_template, abort, redirect, url_for

from app.models import BlogPost

blog = Blueprint('blog', __name__)

@blog.route('/blog', methods=['GET'])
def index():
    """View recent blog posts.

    **Route:** ``/blog``

    **Methods:** ``GET``
    """
    blog_posts = list(BlogPost.objects(published=True).order_by('-date_published')[:10])
    previous_index = None
    next_index = 1
    return render_template('blog/blog.html',
                           posts=blog_posts,
                           previous_index=previous_index,
                           next_index=next_index)

@blog.route('/blog/<int:index>', methods=['GET'])
def blog_archive(index):
    """View older blog posts.

    **Route:** ``/blog/<index>``

    **Methods:** ``GET``
    """
    index = int(index)

    if index <= 0:
        return redirect(url_for('.index'))


    blog_posts = BlogPost.objects(published=True).order_by('-date_published')
    if len(blog_posts) < 10*(index+1):
        next_index = None
    else:
        next_index = index + 1
    previous_index = index - 1
    return render_template('blog/blog.html',
                           posts=list(blog_posts[10*index:10*(index+1)]),
                           previous_index=previous_index,
                           next_index=next_index)

@blog.route('/blog/post/<slug>', methods=['GET'])
def post(slug):
    """View an individual blog post.

    **Route:** ``/blog/post/<slug>``

    **Methods:** ``GET``
    """
    if BlogPost.objects(slug=slug).count() != 1:
        abort(404)
    post = BlogPost.objects().get(slug=slug)

    recent_posts = BlogPost.objects(published=True,
                                    id__ne=post.id,
                                    featured_image__ne=None).order_by('-date_published')[:3]
    if not post.published:
        abort(404)
    return render_template('blog/post.html',
                           post=post,
                           recent_posts=recent_posts)

app/routes/client.py
"""
.. module:: client
    :synopsis: All routes on the ``client`` Blueprint.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

from app import adi
import json
from flask import Blueprint, render_template, abort, redirect, url_for, request
from app.models import Event, BlogPost
from datetime import datetime, date, timedelta
from mongoengine import Q

client = Blueprint('client', __name__)

_resources = None
_labs_data = None
_companies = None

@client.route('/', methods=['GET'])
def index():
    """View the ADI homepage.

    **Route:** ``/``

    **Methods:** ``GET``
    """

    all_events = (Event.objects(
        Q(published=True,
          end_date__gt=date.today()) |
        Q(published=True,
          end_date=date.today(),
          end_time__gt=datetime.now().time())))
    events = all_events.order_by('start_date', 'start_time')[:4]

    all_blog_posts = BlogPost.objects(published=True).order_by('-date_published')
    blog_post = all_blog_posts[0] if all_blog_posts else None

    return render_template('index.html',
                           events=events,
                           blog_post=blog_post)

@client.route('/events/devfest', methods=['GET'])
@client.route('/devfest', methods=['GET'])
def devfest():
    """View the DevFest landing page.

    **Route:** ``/devfest``, ``/events/devfest``

    **Methods:** ``GET``
    """
    return redirect("http://devfe.st")

@client.route('/contact', methods=['GET'])
def contact():
    """View contact information.

    **Route:** ``/contact``

    **Methods:** ``GET``
    """
    return render_template('contact.html')

@client.route('/feedback', methods=['GET'])
def feedback():
    """Submit feedback on past ADI events.

    **Route:** ``/feedback``

    **Methods:** ``GET``
    """
    return render_template('feedback.html')

@client.route('/jobfair', methods=['GET'])
def jobfair():
    """View the ADI Startup Career Fair page.

    **Route:** ``/jobfair``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    companies = _get_companies(force=force)
    return render_template('jobfair.html', companies=companies)

def _get_companies(force=False):
    global _companies
    if not _companies or force:
        with open(adi['COMPANIES_PATH']) as f:
            _companies = json.loads(f.read()).get('companies')
    return _companies

@client.route('/labs', methods=['GET'])
def labs():
    """View information about ADI Labs

    **Route:** ``/labs``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    labs_data = _get_labs_data(force=force)
    return render_template('labs.html', data=labs_data)

def _get_labs_data(force=False):
    global _labs_data
    if not _labs_data or force:
        with open(adi['LABS_DATA_PATH']) as f:
            _labs_data = json.loads(f.read())
    return _labs_data

@client.route('/learn', methods=['GET'])
def learn():
    """Alias for :func:`resources`.

    **Route:** ``/learn``

    **Methods:** ``GET``
    """
    return redirect(url_for('.resources'))

@client.route('/resources', methods=['GET'])
def resources():
    """Learn to code! View resources for learning how to program different
    websites.

    **Route:** ``/resources``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    resources_data = _get_resources(force=force)
    return render_template('resources.html', resources=resources_data)

def _get_resources(force=False):
    global _resources
    if not _resources or force:
        with open(adi['RESOURCES_PATH']) as f:
            _resources = json.loads(f.read())
    return _resources

@client.route('/events', methods=['GET'])
def events():
    """View the latest events.

    **Route:** ``/events``

    **Methods:** ``GET``
    """
    today = date.today()
    last_sunday = datetime.combine(today - timedelta(days=today.isoweekday()+7),
                                   datetime.min.time())
    next_sunday = datetime.combine(today + timedelta(days=7-today.isoweekday()),
                                   datetime.min.time())
    recent_and_upcoming = Event.objects(published=True).order_by('start_date',
                                                                 'start_time')

    recent_events = recent_and_upcoming.filter(end_date__lt=today)[:6]

    events_this_week = recent_and_upcoming.filter(end_date__gte=today,
                                                  start_date__lt=next_sunday)

    upcoming_events = recent_and_upcoming.filter(start_date__gt=next_sunday)[:4]

    more_past_events = bool(Event.objects(published=True,
                                          start_date__lte=last_sunday).count())

    return render_template('events/events.html',
                           recent_events=recent_events,
                           events_this_week=events_this_week,
                           upcoming_events=upcoming_events,
                           more_past_events=more_past_events)

@client.route('/events/<int:index>', methods=['GET'])
def event_archive(index):
    """View old events.

    **Route:** ``/events/<index>``

    **Methods:** ``GET``

    :param int index: The page to fetch
    """
    index = int(index)
    if index <= 0:
        return redirect(url_for('.events'))

    today = date.today()
    last_sunday = datetime.combine(today - timedelta(days=today.weekday()+7),
                                   datetime.min.time())

    past_events=Event.objects(published=True,
                              end_date__lt=today).order_by('start_date')

    if not past_events:
        return redirect(url_for('.events'))

    previous_index = index - 1
    next_index = index + 1 if len(past_events) > 10*index else None
    return render_template('events/archive.html',
                           events=past_events[10*(index-1):10*(index)],
                           previous_index=previous_index,
                           next_index=next_index)

@client.route('/events/<slug>', methods=['GET'])
def event(slug):
    """View a specific non-recurring event, or the next upcoming instance of
    a recurring event.

    **Route:** ``/events/<slug>``

    **Methods:** ``GET``

    :param str slug: The unique slug ID for the post.
    """
    if Event.objects(published=True, slug=slug).count() == 0:
        abort(404) # Either invalid event ID or duplicate IDs.

    event = Event.objects(published=True, slug=slug)[0]


    if event.is_recurring:
        upcoming_event_instances = Event.objects(published=True,
                                                 start_date__gte=date.today(),
                                                 slug=slug).order_by('start_date')
        if upcoming_event_instances:
            event = upcoming_event_instances[0]
        else:
            event = event.parent_series.events[-1]

        upcoming_events = Event.objects(published=True,
                                        start_date__gte=date.today(),
                                        id__ne=event.id).order_by('start_date')[:3]


        return render_template('events/event.html',
                               event=event,
                               upcoming_events=upcoming_events)

    upcoming_events = Event.objects(published=True,
                                    start_date__gte=date.today(),
                                    id__ne=event.id).order_by('start_date')[:3]

    return render_template('events/event.html',
                           event=event,
                           upcoming_events=upcoming_events)

@client.route('/events/<slug>/<index>', methods=['GET'])
def recurring_event(slug, index):
    """View a specific instance of a recurring event.

    **Route:** ``/events/<slug>/<index>``

    **Methods:** ``GET``

    :param str slug: The unique slug ID for the post.
    :param int index: The instance of the event to fetch.
    """
    if Event.objects(published=True, slug=slug).count() == 0:
        abort(404) # Either invalid event ID or duplicate IDs.

    index = int(index)

    event = Event.objects(published=True, slug=slug)[0]

    upcoming_events = Event.objects(published=True,
                                    start_date__gte=date.today(),
                                    id__ne=event.id).order_by('start_date')[:3]


    if not event.is_recurring or not event.parent_series:
        return redirect(url_for('.event', slug=slug))

    if len(event.parent_series.events) <= index:
      abort(404)

    event = event.parent_series.events[index]
    return render_template('events/event.html',
                           event=event,
                           upcoming_events=upcoming_events)

app/templates/blog/blog.html
{% extends 'page.html' %}
{% block title %}Blog | {{ super() }}{% endblock %}
{% import 'macros.html' as macros %}

{% block header_image %}/static/img/hero/writing.jpg{% endblock %}

{% block css %}
{{ super() }}
{% assets "scss_blog" %}
<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{% endassets %}
<link rel="stylesheet" href="{{url_for('static', filename='css/lib/epiceditor/preview/github-highlighted.css')}}">
{% endblock %}

{% block js %}
{{ super() }}
<script src="//yandex.st/highlightjs/8.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block main %}
<section class="tagline">
    <h1>Blog</h1>
</section>
<section class="card top-card">
    <div class="content">
        <div class="section-header">
            <h4>Latest Posts</h4>
            <span class="bar green"></span>
        </div>
        {% for post in posts[:5] %}
        {{ macros.post(post) }}
        {% endfor %}
    </div>
</section>
<section class="full yellow callout">
    <div class="content">
        <div class="callout-left">
            <div class="section-header">
                <h4>Interested in writing for the ADI Blog?</h4>
                <span class="bar gray"></span>
            </div>
            <h3>Send your topic ideas to our blog team.</h3>
            <h3>Once approved, we'll send you further steps!</h3>
            <div class="button-group">
                <div class="button gray">
                    <a href="mailto:blog@adicu.com?subject=Blog Topic Submission">
                        blog@adicu.com
                    </a>
                </div>
            </div>
        </div>
        <div class="callout-right">
            <div class="card">
                <a href="{{ url_for('client.contact') }}">
                    <i style="background-image:url({{ url_for('static', filename='img/hero/hello.jpg') }})"></i>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="card top-card">
    <div class="content">
        {% for post in posts[5:] %}
        {{ macros.post(post) }}
        {% endfor %}
    </div>
</section>
<section>
    <div class="content">
        <div class="pagination">
            <div class="previous">
                {% if previous_index >= 0 %}
                <a href="{{ url_for('blog.blog_archive', index=previous_index) }}">
                    <p><i class="fa fa-chevron-left"></i>Previous</p>
                </a>
                {% endif %}
            </div>
            <div class="next">
                {% if next_index >= 0 %}
                <a href="{{ url_for('blog.blog_archive', index=next_index) }}">
                    <p>Next<i class="fa fa-chevron-right"></i></p>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/blog/post.html
{% extends 'page.html' %}
{% block title %}{{ post.title }} | {{ super() }}{% endblock %}
{% import "macros.html" as macros %}

{% set should_include_hero = False%}

{% block author %}{{post.author.name}}{% endblock %}

{% block metaDescription %}
{{post.snippet(length=40, newlines=False, tags=False) | safe}}
{% endblock %}

{% block css %}
{{ super() }}
{% assets "scss_blog" %}
<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{% endassets %}

<link rel="stylesheet" href="//yandex.st/highlightjs/8.0/styles/github.min.css">
{% endblock %}

{% block js%}
{{ super() }}
<script src="//yandex.st/highlightjs/8.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block heroclass %}hidden{% endblock %}
{% block hero %}
{% endblock %}

{% block mainclass %}no-hero{% endblock %}
{% block main %}
<section class="single post">
    <div class="content">
        {% if post.featured_image %}
        <i class="image"
           style="background-image:url({{ post.featured_image.url() }})"></i>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <div class="details">
            <div class="section-header">
                <h4>{{ post.human_readable_date() }}</h4>
                <span class="bar yellow"></span>
            </div>
            <i class="author" style="background-image:url({{ post.author.get_profile_picture() }})"></i>
            <span class="author">{{post.author.name}}</span>

        </div>
        <div class="text">
            {{ post.html_content | safe }}
        </div>
    </div>
</section>
<section>
    <div class="content">
        <div class="section-header">
            <h4>Recent Posts</h4>
            <span class="bar blue"></span>
        </div>
        <div class="triple">
            {% for p in recent_posts %}
                {{ macros.small_post(p) }}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock main %}