app/routes/client.py
"""
.. module:: client
    :synopsis: All routes on the ``client`` Blueprint.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

from app import adi
import json
from flask import Blueprint, render_template, abort, redirect, url_for, request
from app.models import Event, BlogPost
from datetime import datetime, date, timedelta
from mongoengine import Q

client = Blueprint('client', __name__)

_resources = None
_labs_data = None
_companies = None

@client.route('/', methods=['GET'])
def index():
    """View the ADI homepage.

    **Route:** ``/``

    **Methods:** ``GET``
    """

    all_events = (Event.objects(
        Q(published=True,
          end_date__gt=date.today()) |
        Q(published=True,
          end_date=date.today(),
          end_time__gt=datetime.now().time())))
    events = all_events.order_by('start_date', 'start_time')[:4]

    all_blog_posts = BlogPost.objects(published=True).order_by('-date_published')
    blog_post = all_blog_posts[0] if all_blog_posts else None

    return render_template('index.html',
                           events=events,
                           blog_post=blog_post)

@client.route('/events/devfest', methods=['GET'])
@client.route('/devfest', methods=['GET'])
def devfest():
    """View the DevFest landing page.

    **Route:** ``/devfest``, ``/events/devfest``

    **Methods:** ``GET``
    """
    return redirect("http://devfe.st")

@client.route('/contact', methods=['GET'])
def contact():
    """View contact information.

    **Route:** ``/contact``

    **Methods:** ``GET``
    """
    return render_template('contact.html')

@client.route('/feedback', methods=['GET'])
def feedback():
    """Submit feedback on past ADI events.

    **Route:** ``/feedback``

    **Methods:** ``GET``
    """
    return render_template('feedback.html')

@client.route('/jobfair', methods=['GET'])
def jobfair():
    """View the ADI Startup Career Fair page.

    **Route:** ``/jobfair``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    companies = _get_companies(force=force)
    return render_template('jobfair.html', companies=companies)

def _get_companies(force=False):
    global _companies
    if not _companies or force:
        with open(adi['COMPANIES_PATH']) as f:
            _companies = json.loads(f.read()).get('companies')
    return _companies

@client.route('/labs', methods=['GET'])
def labs():
    """View information about ADI Labs

    **Route:** ``/labs``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    labs_data = _get_labs_data(force=force)
    return render_template('labs.html', data=labs_data)

def _get_labs_data(force=False):
    global _labs_data
    if not _labs_data or force:
        with open(adi['LABS_DATA_PATH']) as f:
            _labs_data = json.loads(f.read())
    return _labs_data

@client.route('/learn', methods=['GET'])
def learn():
    """Alias for :func:`resources`.

    **Route:** ``/learn``

    **Methods:** ``GET``
    """
    return redirect(url_for('.resources'))

@client.route('/resources', methods=['GET'])
def resources():
    """Learn to code! View resources for learning how to program different
    websites.

    **Route:** ``/resources``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    resources_data = _get_resources(force=force)
    return render_template('resources.html', resources=resources_data)

def _get_resources(force=False):
    global _resources
    if not _resources or force:
        with open(adi['RESOURCES_PATH']) as f:
            _resources = json.loads(f.read())
    return _resources

@client.route('/events', methods=['GET'])
def events():
    """View the latest events.

    **Route:** ``/events``

    **Methods:** ``GET``
    """
    today = date.today()
    last_sunday = datetime.combine(today - timedelta(days=today.isoweekday()+7),
                                   datetime.min.time())
    next_sunday = datetime.combine(today + timedelta(days=7-today.isoweekday()),
                                   datetime.min.time())
    recent_and_upcoming = Event.objects(published=True).order_by('start_date',
                                                                 'start_time')

    recent_events = recent_and_upcoming.filter(end_date__lt=today)[:6]

    events_this_week = recent_and_upcoming.filter(end_date__gte=today,
                                                  start_date__lt=next_sunday)

    upcoming_events = recent_and_upcoming.filter(start_date__gt=next_sunday)[:4]

    more_past_events = bool(Event.objects(published=True,
                                          start_date__lte=last_sunday).count())

    return render_template('events/events.html',
                           recent_events=recent_events,
                           events_this_week=events_this_week,
                           upcoming_events=upcoming_events,
                           more_past_events=more_past_events)

@client.route('/events/<int:index>', methods=['GET'])
def event_archive(index):
    """View old events.

    **Route:** ``/events/<index>``

    **Methods:** ``GET``

    :param int index: The page to fetch
    """
    index = int(index)
    if index <= 0:
        return redirect(url_for('.events'))

    today = date.today()
    last_sunday = datetime.combine(today - timedelta(days=today.weekday()+7),
                                   datetime.min.time())

    past_events=Event.objects(published=True,
                              end_date__lt=today).order_by('start_date')

    if not past_events:
        return redirect(url_for('.events'))

    previous_index = index - 1
    next_index = index + 1 if len(past_events) > 10*index else None
    return render_template('events/archive.html',
                           events=past_events[10*(index-1):10*(index)],
                           previous_index=previous_index,
                           next_index=next_index)

@client.route('/events/<slug>', methods=['GET'])
def event(slug):
    """View a specific non-recurring event, or the next upcoming instance of
    a recurring event.

    **Route:** ``/events/<slug>``

    **Methods:** ``GET``

    :param str slug: The unique slug ID for the post.
    """
    if Event.objects(published=True, slug=slug).count() == 0:
        abort(404) # Either invalid event ID or duplicate IDs.

    event = Event.objects(published=True, slug=slug)[0]


    if event.is_recurring:
        upcoming_event_instances = Event.objects(published=True,
                                                 start_date__gte=date.today(),
                                                 slug=slug).order_by('start_date')
        if upcoming_event_instances:
            event = upcoming_event_instances[0]
        else:
            event = event.parent_series.events[-1]

        upcoming_events = Event.objects(published=True,
                                        start_date__gte=date.today(),
                                        id__ne=event.id).order_by('start_date')[:3]


        return render_template('events/event.html',
                               event=event,
                               upcoming_events=upcoming_events)

    upcoming_events = Event.objects(published=True,
                                    start_date__gte=date.today(),
                                    id__ne=event.id).order_by('start_date')[:3]

    return render_template('events/event.html',
                           event=event,
                           upcoming_events=upcoming_events)

@client.route('/events/<slug>/<index>', methods=['GET'])
def recurring_event(slug, index):
    """View a specific instance of a recurring event.

    **Route:** ``/events/<slug>/<index>``

    **Methods:** ``GET``

    :param str slug: The unique slug ID for the post.
    :param int index: The instance of the event to fetch.
    """
    if Event.objects(published=True, slug=slug).count() == 0:
        abort(404) # Either invalid event ID or duplicate IDs.

    index = int(index)

    event = Event.objects(published=True, slug=slug)[0]

    upcoming_events = Event.objects(published=True,
                                    start_date__gte=date.today(),
                                    id__ne=event.id).order_by('start_date')[:3]


    if not event.is_recurring or not event.parent_series:
        return redirect(url_for('.event', slug=slug))

    if len(event.parent_series.events) <= index:
      abort(404)

    event = event.parent_series.events[index]
    return render_template('events/event.html',
                           event=event,
                           upcoming_events=upcoming_events)

app/templates/events/archive.html
{% extends "page.html" %}
{% block title %}Events Archive | {{ super() }}{% endblock %}

{% block header_image %}/static/img/hero/events.jpg{% endblock %}

{% block main %}
<section class="tagline">
    <h1>Past Events</h1>
</section>
<section class="card top-card">
    <div class="content">
        {% for event in events %}
            {{ macros.event(event) }}
        {% endfor %}
    </div>
</section>
<section>
    <div class="content">
        <div class="pagination">
            <div class="previous">
                {% if previous_index >= 0 %}
                <a href="{{ url_for('client.event_archive', index=previous_index) }}">
                    <p><i class="fa fa-chevron-left"></i>Newer</p>
                </a>
                {% endif %}
            </div>
            <div class="next">
                {% if next_index >= 0 %}
                <a href="{{ url_for('client.event_archive', index=next_index) }}">
                    <p>Older<i class="fa fa-chevron-right"></i></p>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock main %}

app/templates/events/event.html
{% extends "page.html" %}
{% block title %}{{ event.title}} | {{ super() }}{% endblock %}
{% import "macros.html" as macros %}

{% set should_include_hero = False%}

{% block css %}
{{ super() }}
{% assets "scss_single_event" %}
<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{% endassets %}
{% endblock %}

{% block heroclass %}hidden{% endblock %}
{% block hero %}
{% endblock %}

{% block mainclass %}no-hero{% endblock %}
{% block main %}
<section class="single single-event">
    <div class="content">
        <i class="image" style="background-image:url({{event.image_url()}})"></i>
        <h1>{{ event.title }}</h1>
        <div class="details">
            <div class="section-header">
                <h4>Details</h4>
                <span class="bar yellow"></span>
            </div>
            {% if event.is_multiday() %}
            <p>
                <i class="fa fa-calendar"></i>
                {{ event.human_readable_datetime() }}
            </p>
            {% else %}
            <p>
                <i class="fa fa-calendar"></i>
                {{ event.human_readable_date() }}
            </p>
            <p>
                <i class="fa fa-clock-o"></i>
                {{ event.human_readable_time() }}
            </p>
            {% endif %}
            <p>
                <i class="fa fa-map-marker"></i>
                {{ event.location }}
            </p>
            {% if event.facebook_url %}
            <a href="{{event.facebook_url}}">
                <div class="button blue">
                    <i class="fa fa-facebook"></i>
                    RSVP on Facebook
                </div>
            </a>

            {% endif %}
        </div>
        <div class="text">
            {{ event.long_description | safe }}
        </div>
    </div>
</section>
<section>
    <div class="content">
        <div class="section-header">
            <h4>Upcoming Events</h4>
            <span class="bar blue"></span>
        </div>
        <div class="triple">
            {% for event in upcoming_events %}
                {{ macros.small_event(event) }}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock main %}

app/templates/events/events.html
{% extends "page.html" %}
{% block title %}Events | {{ super() }}{% endblock %}

{% block header_image %}/static/img/hero/group.jpg{% endblock %}

{% block main %}
<section class="tagline">
    <h1>Events</h1>
</section>
{% if events_this_week %}
<section class="card top-card">
    <div class="content">
        <div class="section-header">
            <h4>This Week</h4>
            <span class="bar green"></span>
        </div>
        {% for event in events_this_week %}
            {{ macros.event(event) }}
        {% endfor %}
    </div>
</section>
{% endif %}
{% if upcoming_events %}
{% if events_this_week %}
<section>
{% else %}
<section class="card top-card">
{% endif %}
    <div class="content">
        <div class="section-header">
            <h4>Upcoming</h4>
            <span class="bar blue"></span>
        </div>
        {% for event in upcoming_events %}
            {{ macros.event(event) }}
        {% endfor %}
    </div>
</section>
{% endif %}
<section class="full green callout">
    <div class="content">
        <div class="callout-left">
            <div class="section-header">
                <a href="{{ url_for('client.event', slug='cookies-and-code') }}">
                <h4>Cookies and Code</h4>
                </a>
                <span class="bar gray"></span>
            </div>
            <h3>Come meet the community. We bring the cookies, you bring the code!</h3>
            <div class="button-group">
                <div class="button gray">
                    <a href="{{ url_for('client.event', slug='cookies-and-code') }}">
                        Find the next Cookies and Code
                    </a>
                </div>
            </div>
        </div>
        <div class="callout-right">
            <div class="card">
                <a href="{{ url_for('client.event', slug='cookies-and-code')}}">
                    <i style="background-image:url({{ url_for('static', filename='img/events/cookie_monster_original.jpg') }})"></i>
                </a>
            </div>
        </div>
    </div>
</section>
{% if recent_events %}
<section>
    <div class="content">
        <div class="section-header">
            <h4>Past Events</h4>
            <span class="bar blue"></span>
        </div>
        {% for triple in range(((recent_events|length) // 3) + 1) %}
        <div class="triple">
            {% for i in range(3) %}
            {% with index = 3 * triple + i %}
            {% if index < (recent_events | length) %}
                {{ macros.small_event(recent_events[index]) }}
            {% endif %}
            {% endwith %}
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</section>
{% endif %}
{% if more_past_events %}
<section>
    <div class="content">
        <div class="pagination">
            <div class="archive">
                <a href="{{ url_for('client.event_archive', index=1) }}">
                    <p>Older events</p>
                </a>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endblock main %}