app/routes/base.py
"""
.. module:: base
    :synopsis: All routes on the ``base`` Blueprint, as well as error handlers,
        before and after request handlers, and context processors.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

import sys
from flask import g, session, render_template, request, redirect, Blueprint
from mongoengine.queryset import DoesNotExist
import requests

from app import app
from app.models import User

SUPER_USER_GPLUS_ID = 'super'

base = Blueprint('base', __name__)

@app.errorhandler(Exception)
def exceptionHandler(error):
    """Handle uncaught exceptions."""
    app.logger.error("Uncaught Exception", exc_info=sys.exc_info())
    app.handle_exception(error) # default error handler

@app.errorhandler(400)
def bad_request(error):
    """Handle 400 errors."""
    return render_template('error/400.html'), 400

@app.errorhandler(401)
def not_authorized(error):
    """Handle 401 errors."""
    return render_template('error/401.html'), 401

@app.errorhandler(403)
def forbidden(error):
    """Handle 403 errors."""
    return render_template('error/403.html'), 403

@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors."""
    old_site_url = 'http://adicu.github.com' + request.path
    try:
        response = requests.head(old_site_url, allow_redirects=True)
        if response.status_code == 200:
            return redirect(old_site_url)
    except requests.exceptions.ConnectionError:
        pass

    return render_template('error/404.html'), 404

@app.errorhandler(405)
def method_not_allowed(error):
    """Handle 405 errors."""
    return render_template('error/405.html', method=request.method), 405

@app.errorhandler(500)
def internal_server_error(error):
    """Handle 500 errors."""
    return render_template('error/500.html'), 500

@app.before_request
def lookup_current_user():
    """Set the g.user variable to the User in the database that shares
    openid with the session, if one exists.

    Note that it gets called before all requests, but not before decorators.
    """
    g.user = None
    if not app.config.get('GOOGLE_AUTH_ENABLED'):
        # bypass auth by mocking a super user
        session['gplus_id'] = SUPER_USER_GPLUS_ID
        try:
            g.user = User.objects.get(gplus_id=SUPER_USER_GPLUS_ID)
        except DoesNotExist:
            user = User(name='Super User',
                        gplus_id=SUPER_USER_GPLUS_ID,
                        user_type='admin',
                        email='email@email.com')
            user.save()

    if 'gplus_id' in session:
        gplus_id = session['gplus_id']
        try:
            g.user = User.objects().get(gplus_id=gplus_id)
        except DoesNotExist:
            pass  # Fail gracefully if the user is not in the database yet

@app.context_processor
def inject_user():
    """Injects a variable named ``current_user`` into all of the Jinja
    templates, so that it can be used at will.
    """
    if hasattr(g, 'user'):
        return dict(current_user=g.user)
    return dict(current_user=None)

@app.after_request
def add_header(response):
    """
    Add headers to both force latest IE rendering engine or Chrome Frame,
    and also to cache the rendered page for 10 minutes.
    """
    response.headers['X-UA-Compatible'] = 'IE=Edge,chrome=1'
    response.headers['Cache-Control'] = 'public, max-age=0'
    return response

app/routes/blog.py
"""
.. module:: blog
    :synopsis: All routes on the ``blog`` Blueprint.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

from flask import Blueprint, render_template, abort, redirect, url_for

from app.models import BlogPost

blog = Blueprint('blog', __name__)

@blog.route('/blog', methods=['GET'])
def index():
    """View recent blog posts.

    **Route:** ``/blog``

    **Methods:** ``GET``
    """
    blog_posts = list(BlogPost.objects(published=True).order_by('-date_published')[:10])
    previous_index = None
    next_index = 1
    return render_template('blog/blog.html',
                           posts=blog_posts,
                           previous_index=previous_index,
                           next_index=next_index)

@blog.route('/blog/<int:index>', methods=['GET'])
def blog_archive(index):
    """View older blog posts.

    **Route:** ``/blog/<index>``

    **Methods:** ``GET``
    """
    index = int(index)

    if index <= 0:
        return redirect(url_for('.index'))


    blog_posts = BlogPost.objects(published=True).order_by('-date_published')
    if len(blog_posts) < 10*(index+1):
        next_index = None
    else:
        next_index = index + 1
    previous_index = index - 1
    return render_template('blog/blog.html',
                           posts=list(blog_posts[10*index:10*(index+1)]),
                           previous_index=previous_index,
                           next_index=next_index)

@blog.route('/blog/post/<slug>', methods=['GET'])
def post(slug):
    """View an individual blog post.

    **Route:** ``/blog/post/<slug>``

    **Methods:** ``GET``
    """
    if BlogPost.objects(slug=slug).count() != 1:
        abort(404)
    post = BlogPost.objects().get(slug=slug)

    recent_posts = BlogPost.objects(published=True,
                                    id__ne=post.id,
                                    featured_image__ne=None).order_by('-date_published')[:3]
    if not post.published:
        abort(404)
    return render_template('blog/post.html',
                           post=post,
                           recent_posts=recent_posts)

app/routes/client.py
"""
.. module:: client
    :synopsis: All routes on the ``client`` Blueprint.

.. moduleauthor:: Dan Schlosser <dan@danrs.ch>
"""

from app import adi
import json
from flask import Blueprint, render_template, abort, redirect, url_for, request
from app.models import Event, BlogPost
from datetime import datetime, date, timedelta
from mongoengine import Q

client = Blueprint('client', __name__)

_resources = None
_labs_data = None
_companies = None

@client.route('/', methods=['GET'])
def index():
    """View the ADI homepage.

    **Route:** ``/``

    **Methods:** ``GET``
    """

    all_events = (Event.objects(
        Q(published=True,
          end_date__gt=date.today()) |
        Q(published=True,
          end_date=date.today(),
          end_time__gt=datetime.now().time())))
    events = all_events.order_by('start_date', 'start_time')[:4]

    all_blog_posts = BlogPost.objects(published=True).order_by('-date_published')
    blog_post = all_blog_posts[0] if all_blog_posts else None

    return render_template('index.html',
                           events=events,
                           blog_post=blog_post)

@client.route('/events/devfest', methods=['GET'])
@client.route('/devfest', methods=['GET'])
def devfest():
    """View the DevFest landing page.

    **Route:** ``/devfest``, ``/events/devfest``

    **Methods:** ``GET``
    """
    return redirect("http://devfe.st")

@client.route('/contact', methods=['GET'])
def contact():
    """View contact information.

    **Route:** ``/contact``

    **Methods:** ``GET``
    """
    return render_template('contact.html')

@client.route('/feedback', methods=['GET'])
def feedback():
    """Submit feedback on past ADI events.

    **Route:** ``/feedback``

    **Methods:** ``GET``
    """
    return render_template('feedback.html')

@client.route('/jobfair', methods=['GET'])
def jobfair():
    """View the ADI Startup Career Fair page.

    **Route:** ``/jobfair``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    companies = _get_companies(force=force)
    return render_template('jobfair.html', companies=companies)

def _get_companies(force=False):
    global _companies
    if not _companies or force:
        with open(adi['COMPANIES_PATH']) as f:
            _companies = json.loads(f.read()).get('companies')
    return _companies

@client.route('/labs', methods=['GET'])
def labs():
    """View information about ADI Labs

    **Route:** ``/labs``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    labs_data = _get_labs_data(force=force)
    return render_template('labs.html', data=labs_data)

def _get_labs_data(force=False):
    global _labs_data
    if not _labs_data or force:
        with open(adi['LABS_DATA_PATH']) as f:
            _labs_data = json.loads(f.read())
    return _labs_data

@client.route('/learn', methods=['GET'])
def learn():
    """Alias for :func:`resources`.

    **Route:** ``/learn``

    **Methods:** ``GET``
    """
    return redirect(url_for('.resources'))

@client.route('/resources', methods=['GET'])
def resources():
    """Learn to code! View resources for learning how to program different
    websites.

    **Route:** ``/resources``

    **Methods:** ``GET``
    """
    force = request.args.get('force') is not None
    resources_data = _get_resources(force=force)
    return render_template('resources.html', resources=resources_data)

def _get_resources(force=False):
    global _resources
    if not _resources or force:
        with open(adi['RESOURCES_PATH']) as f:
            _resources = json.loads(f.read())
    return _resources

@client.route('/events', methods=['GET'])
def events():
    """View the latest events.

    **Route:** ``/events``

    **Methods:** ``GET``
    """
    today = date.today()
    last_sunday = datetime.combine(today - timedelta(days=today.isoweekday()+7),
                                   datetime.min.time())
    next_sunday = datetime.combine(today + timedelta(days=7-today.isoweekday()),
                                   datetime.min.time())
    recent_and_upcoming = Event.objects(published=True).order_by('start_date',
                                                                 'start_time')

    recent_events = recent_and_upcoming.filter(end_date__lt=today)[:6]

    events_this_week = recent_and_upcoming.filter(end_date__gte=today,
                                                  start_date__lt=next_sunday)

    upcoming_events = recent_and_upcoming.filter(start_date__gt=next_sunday)[:4]

    more_past_events = bool(Event.objects(published=True,
                                          start_date__lte=last_sunday).count())

    return render_template('events/events.html',
                           recent_events=recent_events,
                           events_this_week=events_this_week,
                           upcoming_events=upcoming_events,
                           more_past_events=more_past_events)

@client.route('/events/<int:index>', methods=['GET'])
def event_archive(index):
    """View old events.

    **Route:** ``/events/<index>``

    **Methods:** ``GET``

    :param int index: The page to fetch
    """
    index = int(index)
    if index <= 0:
        return redirect(url_for('.events'))

    today = date.today()
    last_sunday = datetime.combine(today - timedelta(days=today.weekday()+7),
                                   datetime.min.time())

    past_events=Event.objects(published=True,
                              end_date__lt=today).order_by('start_date')

    if not past_events:
        return redirect(url_for('.events'))

    previous_index = index - 1
    next_index = index + 1 if len(past_events) > 10*index else None
    return render_template('events/archive.html',
                           events=past_events[10*(index-1):10*(index)],
                           previous_index=previous_index,
                           next_index=next_index)

@client.route('/events/<slug>', methods=['GET'])
def event(slug):
    """View a specific non-recurring event, or the next upcoming instance of
    a recurring event.

    **Route:** ``/events/<slug>``

    **Methods:** ``GET``

    :param str slug: The unique slug ID for the post.
    """
    if Event.objects(published=True, slug=slug).count() == 0:
        abort(404) # Either invalid event ID or duplicate IDs.

    event = Event.objects(published=True, slug=slug)[0]


    if event.is_recurring:
        upcoming_event_instances = Event.objects(published=True,
                                                 start_date__gte=date.today(),
                                                 slug=slug).order_by('start_date')
        if upcoming_event_instances:
            event = upcoming_event_instances[0]
        else:
            event = event.parent_series.events[-1]

        upcoming_events = Event.objects(published=True,
                                        start_date__gte=date.today(),
                                        id__ne=event.id).order_by('start_date')[:3]


        return render_template('events/event.html',
                               event=event,
                               upcoming_events=upcoming_events)

    upcoming_events = Event.objects(published=True,
                                    start_date__gte=date.today(),
                                    id__ne=event.id).order_by('start_date')[:3]

    return render_template('events/event.html',
                           event=event,
                           upcoming_events=upcoming_events)

@client.route('/events/<slug>/<index>', methods=['GET'])
def recurring_event(slug, index):
    """View a specific instance of a recurring event.

    **Route:** ``/events/<slug>/<index>``

    **Methods:** ``GET``

    :param str slug: The unique slug ID for the post.
    :param int index: The instance of the event to fetch.
    """
    if Event.objects(published=True, slug=slug).count() == 0:
        abort(404) # Either invalid event ID or duplicate IDs.

    index = int(index)

    event = Event.objects(published=True, slug=slug)[0]

    upcoming_events = Event.objects(published=True,
                                    start_date__gte=date.today(),
                                    id__ne=event.id).order_by('start_date')[:3]


    if not event.is_recurring or not event.parent_series:
        return redirect(url_for('.event', slug=slug))

    if len(event.parent_series.events) <= index:
      abort(404)

    event = event.parent_series.events[index]
    return render_template('events/event.html',
                           event=event,
                           upcoming_events=upcoming_events)

app/templates/contact.html
{% extends "page.html" %}
{% block title %}Contact | {{ super() }}{% endblock %}

{% block header_image %}/static/img/hero/contact.jpg{% endblock %}

{% block main %}
<section class="tagline">
    <h1>Contact</h1>
</section>
<section class="card top-card">
    <div class="content">
        <div class="section-header">
            <h4>Come meet ADI</h4>
            <span class="bar blue"></span>
        </div>
        <h3>Interested in learning more about ADI?  The best way to get to know
            us better is by coming to
            <a href="{{ url_for('client.event', slug='cookies-and-code') }}">Cookies and Code</a>,
            Wednesdays from 10pm-midnight in Lerner 569. People of all experience
            levels are welcome to come by, meet our members, work on personal
            projects, and eat free cookies! What could be better?</h3>
        <div class="button-group centered">
            <div class="blue button">
                <a href="{{ url_for('client.event', slug='cookies-and-code') }}">
                    Find the next Cookies and Code
                </a>
            </div>
        </div>
    </div>
</section>
<section class="full green callout">
    <div class="content">
        <div class="callout-left">
            <div class="section-header">
                <h4>Jobs</h4>
                <span class="bar gray"></span>
            </div>
            <h3>Have a job opportunity or looking for one yourself?  Check out the CORE Jobs Board!</h3>
            <div class="button-group">
                <div class="button gray"><a target="_blank" href="http://jobs.coreatcu.com">Launch</a></div>
            </div>
        </div>
        <div class="callout-right">
            <div class="card">
                <a href="http://jobs.coreatcu.com">
                    <i style="background-image:url({{ url_for('static', filename='img/jobs.png') }})"></i>
                </a>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="content">
        <div class="section-header">
            <h4>Send us an Email</h4>
            <span class="bar blue"></span>
        </div>
        <ul class="contact-options">
            <li>
                <h3>Networking</h3>
                <p>Part of the NYC startup community or an established business? Reach out to Columbia hackers.</p>
                <div class="button-group centered">
                    <div class="blue button">
                        <a href="mailto://networking@adicu.com">
                           networking@adicu.com
                        </a>
                    </div>
                </div>
            </li>
            <li>
                <h3>Workshops</h3>
                <p>Host a workshop with us. We'll take care of the details so you can focus on what's important: teaching.</p>
                <div class="button-group centered">
                    <div class="blue button">
                        <a href="mailto://workshops@adicu.com">
                            workshops@adicu.com
                        </a>
                    </div>
                </div>
            </li>
        </ul>
        <ul class="contact-options">
            <li>
                <h3>Social</h3>
                <p>Co-sponsor an campus event with us, we put the "Fun" in "Fundamentals of Computer Science".</p>
                <div class="button-group centered">
                    <div class="blue button">
                        <a href="mailto://social@adicu.com">
                            social@adicu.com
                        </a>
                    </div>
                </div>
            </li>
            <li>
                <h3>Infrastructure</h3>
                <p>Help make ADI's technical projects better by suggesting cool features and providing feedback.</p>
                <div class="button-group centered">
                    <div class="blue button">
                        <a href="mailto://infrastructure@adicu.com">
                            infrastructure@adicu.com
                        </a>
                    </div>
                </div>
            </li>
        </ul>
        {% if events %}
        {{ macros.event(events[0]) }}
        {% endif %}
    </div>
</section>
{% endblock main %}

app/templates/index.html
{% extends "page.html" %}

{% block css %}
{{ super() }}
{% assets "scss_blog" %}
<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{% endassets %}
{% endblock %}


{% block main %}
<section class="tagline">
    <h1>All things tech at Columbia</h1>
</section>
<section class="card top-card">
    <div class="content">

        <form action="//adicu.us4.list-manage.com/subscribe/post?u=62d8b690f349b99dd7e0f3205&amp;id=01a495e6ed"
              method="post"
              id="gi-embedded-subscribe-form"
              name="gi-embedded-subscribe-form"
              class="subscribe validate"
              target="_blank">
            <div class="left">
                <input type="email"
                       name="EMAIL"
                       id="gi-EMAIL"
                       placeholder="Subscribe to our newsletter..."
                       required />
            </div>
            <div class="button submit">Sign Up!</div>
            <input class="hidden"
                   type="submit"
                   id="gi-embedded-subscribe"
                   name="subscribe">
        </form>
    </div>
</section>
<section>
    <div class="content">
        <div class="section-header">
            <h4>What We do</h4>
            <span class="bar yellow"></span>
        </div>
        <h3>The Application Development Initiative seeks to nurture student creativity and technological aptitude by creating a community and resources for student developers of all talents and interests.</h3>
    </div>
</section>
{% if events | length  > 0 %}
<section>
    <div class="content">
        <div class="section-header">
            <h4>Events</h4>
            <span class="bar blue"></span>
        </div>
        {% if events %}
        {{ macros.event(events[0]) }}
        {% endif %}
    </div>
</section>
{% endif %}
{% if events | length > 1 %}
<section>
    <div class="content">
        <div class="section-header">
            <h4>Upcoming</h4>
            <span class="bar green"></span>
        </div>
        <div class="triple">
            {% if events %}
            {% for index in range(1,(events|length)) %}
            {{ macros.small_event(events[index]) }}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
{% endif %}
<section class="full yellow callout">
    <div class="content">
        <div class="callout-left">
            <div class="section-header">
                <h4>Learn to Code</h4>
                <span class="bar gray"></span>
            </div>
            <h3>We've collected everything you need to learn to make your first app.</h3>
            <div class="button-group">
                <div class="button gray"><a href="{{ url_for('client.resources') }}">Learn to Code</a></div>
            </div>
            <p>Or, apply your knowledge with <a href="{{ url_for('client.labs') }}">ADI Labs</a></p>
        </div>
        <div class="callout-right">
            <div class="card">
                <a href="http://courses.adicu.com">
                    <i style="background-image:url({{ url_for('static', filename='img/learn.jpg') }})"></i>
                </a>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="content">
        <div class="section-header">
            <h4>From our Blog</h4>
            <span class="bar blue"></span>
        </div>
        <div class="triple">
            {% if blog_post %}
                {{ macros.post(blog_post) }}
            {% endif %}
        </div>
    </div>
</section>
{% endblock main %}

app/templates/macros.html
{% macro render_field(field, label=False, placeholder=None, hidden=None) %}
{% if field.errors %}
<div class="form-component {{ wrapper_class }} error">
{% elif field.flags.error %}
<div class="form-component {{ wrapper_class }} flag">
{% elif hidden %}
<div class="form-component {{ wrapper_class }} hidden">
{% else%}
<div class="form-component {{ wrapper_class }}">
{% endif %}
    {% set css_class = 'form-control ' + kwargs.pop('class', '') %}
    {% if label %}{{ field.label }}{% endif %}
    {{ field(class=css_class, placeholder=placeholder, **kwargs) }}
</div>
{% endmacro %}

{% macro modal(modal="modal") %}
<div class="opaque hidden" data-modal="{{ modal }}">
    <div class="modal-wrapper">
        <span class="close-modal">
            <a href="#close-modal" data-modal="{{ modal }}">
                <i class="fa fa-times fa-2x"></i>
            </a>
        </span>
        <div class="modal">
            {{ caller() }}
        </div>
    </div>
</div>
{% endmacro %}

{% macro toggle(on, off, start_on=True) %}
<div class="toggle-wrapper {% if start_on %}active{% endif %}">
    <a href="#toggle">
        <span class="on">
            <span class="inner">{{ off }}</span>
        </span>
        <span class="off">
            <span class="inner">{{ on }}</span>
        </span>
        <span class="label">
            <i class="fa fa-arrow-right"></i>
        </span>
    </a>
</div>
{% endmacro %}

{% macro confirm(text, action) %}
<div class="confirm-wrapper">
    <div class="confirm confirm-hidden">
        <form class="confirm-form" method="POST" action="{{ action }}">
            <input class="confirm-cancel" value="Cancel" type="button" />
            {% if caller %}
            <div class="confirm-confirm">
                {{ caller() }}
            </div>
            {% else %}
            <input class="confirm-confirm" value="Confirm" type="submit" />
            {% endif %}
        </form>
    </div>
    <a href="#open-confirm" class="confirm-prompt btn">{{ text }}</a>
</div>
{% endmacro %}


{% macro upload_form(form, uploaded_from="") %}
<form class="upload-form" action="{{ url_for('media.upload') }}" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="hidden-but-not-forgotten">
        {{ render_field(form.image) }}
        {{ render_field(form.extension) }}
        {{ render_field(form.uploaded_from, value=uploaded_from)}}
        <input type="submit" value="Upload">
    </div>
    <div class="btn btn-choose">Choose File</div>
    <div class="filename-wrapper">
        {{ render_field(form.filename, label=False, placeholder="No File Chosen", required="")}}
        <span class="extension"></span>
    </div>
    <div class="btn btn-upload">Upload</div>
</form>
{% endmacro %}


{% macro navbar(navbar_items) %}
<div class="navbar">
    <div class="content">
        <nav>
            <a href="/">
                <img class="logo"src="{{ url_for('static', filename='img/logo/adi-logo-tiny.png') }}">
            </a>
            <div class="right">
                <ul class="menu">
                    {% for label, url in navbar_items %}
                    <li>
                        <a href="{{url}}">
                            <div>{{ label }}</div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </nav>
    </div>
</div>
{% endmacro %}

{% macro event(event, show_description=True) %}
<div class="event large">
    <div class="image">
        <a href="{{ event.get_absolute_url() }}">
            <i style="background-image:url({{ event.image_url() }});"></i>
        </a>
    </div>
    <div class="text">
        <a href="{{ event.get_absolute_url() }}">
            <h2>{{ event.title }}</h2>
        </a>
        {% if show_description %}
        <p class="description">{{ event.short_description | safe }}</p>
        {% endif %}
        <div class="details">
            {% if event.is_multiday() %}
            <p>
                <i class="fa fa-calendar"></i>
                {{ event.human_readable_datetime() }}
            </p>
            {% else %}
            <p>
                <i class="fa fa-calendar"></i>
                {{ event.human_readable_date() }}
            </p>
            <p>
                <i class="fa fa-clock-o"></i>
                {{ event.human_readable_time() }}
            </p>
            {% endif %}
            <p>
                <i class="fa fa-map-marker"></i>
                {{ event.location }}
            </p>
        </div>
    </div>
</div>
{% endmacro %}

{% macro small_event(event) %}
<div class="event small-event small">
    <div class="inner">
        <a href="{{ event.get_absolute_url() }}">
            <i class="image" style="background-image:url({{event.image_url()}});"></i>
        </a>
        <div class="text">
            <a href="{{ url_for('client.event', slug=event.slug) }}">
                <h5>{{ event.title }}</h5>
            </a>
            <div class="details">
                {% if event.is_multiday() %}
                <p>
                    <i class="fa fa-calendar"></i>
                    {{ event.human_readable_datetime() }}
                </p>
                {% else %}
                <p>
                    <i class="fa fa-calendar"></i>
                    {{ event.human_readable_date() }}
                </p>
                <p>
                    <i class="fa fa-clock-o"></i>
                    {{ event.human_readable_time() }}
                </p>
                {% endif %}
                <p>
                    <i class="fa fa-map-marker"></i>
                    {{ event.location }}
                </p>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

{% macro post(post) %}
<div class="post large">
    {% if post.featured_image %}
    <div class="image">
        <a href="{{ post.get_absolute_url() }}">
            <i style="background-image:url({{ post.featured_image.url() }});"></i>
        </a>
    </div>
    <div class="text with-image">
    {% else %}
    <div class="text">
    {% endif %}
        <a href="{{ post.get_absolute_url() }}">
            <h2>{{ post.title }}</h2>
        </a>
        <p class="date">{{ post.human_readable_date() }}</p>
        <p class="author">by {{post.author.name}}</p>
        {{ post.snippet(30) | safe }}
    </div>
</div>
{% endmacro %}

{% macro small_post(post) %}
<div class="post small">
    <div class="inner">
        <a href="{{ post.get_absolute_url() }}">
            <i class="image" style="background-image:url({{post.featured_image.url()}});"></i>
        </a>
        <div class="text">
            <a href="{{ url_for('blog.post', slug=post.slug) }}">
                <h5>{{ post.title }}</h5>
            </a>
            <i class="fa fa-file-text-o"></i>
            <p class="date">{{ post.human_readable_date() }}</p>
            <p class="author">by {{post.author.name}}</p>
        </div>
    </div>
</div>
{% endmacro %}

app/templates/page.html
{% extends "base.html" %}
{% block title %}ADI | The Application Development Initiative{% endblock %}
{% import "macros.html" as macros %}

{% block css %}
{{ super() }}
{% assets "scss_client" %}
<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{% endassets %}
{% endblock %}

{% block js %}
{{ super() }}
<script src="//cdn.jsdelivr.net/mobile-detect.js/0.4.3/mobile-detect.min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/home/home.js') }}"></script>
{% endblock %}


{% block fonts %}
{{ super() }}
<link href='//fonts.googleapis.com/css?family=Roboto+Slab|Merriweather+Sans:300,400,700,400italic' rel='stylesheet' type='text/css'>
{% endblock %}

{% set navbar_items = [('Events', '/events'),
('Resources', '/resources'),
('Labs', '/labs'),
('Blog', '/blog'),
('Contact', '/contact')] %}

{%- block body -%}
<div class="all-wrapper">
    {% if config['DEVFEST_BANNER'] %}
    <div class="devfest-banner">
        <a href="http://devfe.st">
            <div class="content">
                <img src="{{ url_for('static', filename='img/devfest-small.png') }}">
                <h5 class="message">
                    If you've ever wanted to build an app, <br><strong>now's the time to learn.</strong>
                </h5>
                <div class="devfest-button">Register Today</div>

            </div>
        </a>
    </div>
    {% endif %}
    <div class="ribbon">
        <div class="ribbon-inner">
            {% for i in range(8) %}
            <span class="ribbon-strip blue"></span>
            <span class="ribbon-strip yellow"></span>
            <span class="ribbon-strip green"></span>
            {% endfor %}
        </div>
    </div>

    {{ macros.navbar(navbar_items) }}

    <div class="hero {% block heroclass %}{% endblock %}">
        {% block hero %}
        <div class="scrim"></div>
        <i style="background-image: url({% block header_image %}/static/img/hero/jane.jpg{% endblock%});"></i>
        {% endblock %}
    </div>
    <div class="main {% block mainclass %}{% endblock %}">
        {% block main %}{% endblock %}
    </div>
    <div class="footer-spacer"></div>
</div>
<footer>
    <div class="content">
        <p>
            Built by <a href="http://danrschlosser.com">Dan Schlosser</a><br>
            Design help from <a href="http://jhil.co">Jeff Hilnbrand</a><br />
            Maintained by <a href="http://adicu.com/labs">ADI Labs</a>
        </p>
        <p class="right">
            This work is licensed under a <br />
            <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/">
                Creative Commons license.
            </a>
        </p>
    </div>
</footer>
{% endblock body %}